### ISSUE TITLE
我问一下这个react支持吗？

### ISSUE THREAD

**Issue by xuxiaoqiang33** [liubin915249126/javascript#1]
我想在react 里面用这个插件，可以做到吗？

**Comment by liubin915249126** [comment]
可以的，可以看我的另一篇文章[在react里面使用jquery插件](https://segmentfault.com/a/1190000011133781)

**Comment by xuxiaoqiang33** [comment]
[嗯。。。我现在的话需要一个功能更加强大的插件，见附件。。你能帮我看看如何在react里面引入这个插件吗(插件地址为(http://www.jq22.com/jquery-info5015)？我按照你发的链接里面的做法好像还是报错的。（万分感谢）？]

**Comment by liubin915249126** [comment]
加下我qq，我帮你看下

**Comment by tiantian000** [comment]
请问楼上的问题解决了吗？两个节点之间最多可以有几条连线？

**Comment by liubin915249126** [comment]
楼上问的是怎样在react里面使用jquery插件，你问的是？

**Comment by tiantian000** [comment]
我说的是流程图的插件，我也是要做一个在线绘制流程图的功能，你的这个插件支持节点间多条连线吗？

**Comment by liubin915249126** [comment]
支持的，两个div之间可以多线连接

**Comment by tiantian000** [comment]
嗯谢谢

**Comment by tiantian000** [comment]
我引入插件会报错，能帮我看一下吗
